language: node_js
node_js: stable
branches:
  only:
  - master
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
before_install:
- git config --global user.name "Roger-luo"
- git config --global user.email "hiroger@qq.com"
# yarn
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- npm install -g hexo-cli
- npm install hexo-math --save
- npm install hexo-generator-searchdb --save
- npm install hexo-deployer-git --save
install:
- yarn
script:
- hexo clean
- hexo generate
after_success:
- sed -i "s/DOCUMENTER_KEY/${DOCUMENTER_KEY}/g" ./_config.yml
- hexo d
# - cd ./public
# - git init
# - git add --all .
# - git commit -m "Travis CI Auto Builder"
# - git remote add origin https://$DOCUMENTER_KEY@github.com/Roger-luo/blog.git
# - git push --force origin origin/gh-pages
