language: node_js
node_js: stable
branches:
  only:
  - master
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
before_install:
- git config --global user.name "Roger-luo"
- git config --global user.email "hiroger@qq.com"
# yarn
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- npm install -g hexo-cli
install:
- yarn
script:
- hexo clean
- hexo generate
after_success:
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
# 这里的 REPO_TOKEN 即之前在 travis 项目的环境变量里添加的
- git push --force https://$DOCUMENTER_KEY@github.com/Roger-luo/blog.git gh-pages
